// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart' show dotenv;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: dotenv.env['API_KEY'] ?? "NULL",
          appId: dotenv.env['APP_ID'] ?? "NULL",
          messagingSenderId: dotenv.env['MESSAGING_SENDER_ID'] ?? "NULL",
          projectId: dotenv.env['PROJECT_ID'] ?? "NULL",
          databaseURL: dotenv.env['DATABASE_URL'] ?? "NULL",
          storageBucket: dotenv.env['STORAGE_BUCKET'] ?? "NULL",
        );
      case TargetPlatform.iOS:
        return FirebaseOptions(
          apiKey: dotenv.env['API_KEY'] ?? "NULL",
          appId: dotenv.env['APP_ID'] ?? "NULL",
          messagingSenderId: dotenv.env['MESSAGING_SENDER_ID'] ?? "NULL",
          projectId: dotenv.env['PROJECT_ID'] ?? "NULL",
          databaseURL: dotenv.env['DATABASE_URL'] ?? "NULL",
          storageBucket: dotenv.env['STORAGE_BUCKET'] ?? "NULL",
          iosClientId: dotenv.env['IOS_CLIENT_ID'] ?? "NULL",
          iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? "NULL",
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
